### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moepoi** [lndmflngs/line-to-telegram#2]
C:\Users\Michael\Downloads>java -jar line-to-telegram.jar https://store.line.me/stickershop/product/6656060/en

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 57, end -1, length 86
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at model.Sticker.getName(Sticker.kt:8)
        at LineToTelegramKt.main(LineToTelegram.kt:12)

**Comment by imbeerus** [comment]
Thanks for response. Everything should work now (´･ω･`)
Just download the [latest version](https://github.com/lndmflngs/line-to-telegram/releases/latest)
