### ISSUE TITLE
Error when pack name contains invalid characters

### ISSUE THREAD

**Issue by ekisu** [lndmflngs/line-to-telegram#4]
```
java -jar line-to-telegram.jar https://store.line.me/stickershop/product/7742899/en
Picked up _JAVA_OPTIONS: -Xmx512m
java.io.FileNotFoundException: C:\Users\kotori\Downloads\"Hitori Bocchi no Marumaruseikatsu" Nako\189407782.png (A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(Unknown Source)
        at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
        at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
        at java.desktop/javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
        at java.desktop/com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
        at java.desktop/javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
        at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
        at utils.Utils.writeToFile(Utils.kt:80)
        at utils.Utils.saveImage(Utils.kt:19)
        at LineToTelegramKt.main(LineToTelegram.kt:12)
Exception in thread "main" javax.imageio.IIOException: Can't create an ImageOutputStream!
        at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
        at utils.Utils.writeToFile(Utils.kt:80)
        at utils.Utils.saveImage(Utils.kt:19)
        at LineToTelegramKt.main(LineToTelegram.kt:12)
```

**Comment by imbeerus** [comment]
Thanks for response. Everything should work now (=^･ω･^=)
Just download the latest version
